apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: NewServiceForm
  title: Onboard new Service
  description: Onboarding a new service
  tags:
    - tf
    - aws
    - gcp
    - azure
spec:
  owner: greg.kroon@harness.io
  type: environment
  parameters:
    - title: Project and Repo Details
      required:
        - owner
        - github_repo
      properties:
        owner:
          title: Choose the Owner
          type: string
          ui:field: OwnerPicker
        github_repo:
          title: What App/Repo will this service be associated with?
          type: string
          description: someRepoName
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
    - title: Service Details
      properties:
        service_type:
          title: Choose a service type
          type: string
          enum: ["Java", "Golang", "Python"]
          default: Java
        cloud_provider:
          title: Choose a cloud provider
          type: string
          enum: ["AWS"]
          default: AWS
        tech_stack:
          title: Choose the Underlying Infra
          type: string
          enum: ["VM"]
          default: VM
        instance_type:
          title: Choose the Instance Type
          type: string
          enum: ["t2.micro", "t2.large", "t3.2xlarge", "other"]
          default: t2.micro
        ami:
          title: Choose desired AMI
          type: string
          enum: ["ami-09ff94ae883853013", "ami-0ff8a91507f77f867", "ami-0ad8219dfgh45742d", "ami-0cf24653bcf894797"]
          default: ami-09ff94ae883853013
        subnet:
          title: Choose desired subnet
          type: string
          enum: ["subnet-16dad05b", "subnet-34da30rt", "subnet-76j1hag5", "subnet-94s21hr1"]
          default: subnet-16dad05b
        vpc:
          title: Choose VPC security group
          type: string
          enum: ["sg-078339fd2b4e5b1a5", "sg-024561fd2344e5brte", "sg-03sdf832dfe5b1n3"]
          default: sg-078339fd2b4e5b1a5
        count:
          title: Choose desired instance count (i.e. How many VMs?)
          type: integer
          default: 1
        sla:
          title: Choose an SLA
          type: string
          enum: ["99.9", "99", "95"]
          default: 99.9
        patchlevel:
          title: Choose a patch level
          type: string
          enum: ["2024-08", "2024-07", "2024-06"]
          default: 2024-08
        osversion:
          title: Choose an OS version
          type: string
          enum: ["Ubuntu 22.04 LTS", "Ubuntu 18.04 LTS", "Ubuntu 16.04 LTS"]
          default: Ubuntu 22.04 LTS
          
  steps:
    - id: trigger
      name: Provisioning your Infrastructure
      action: trigger:harness-custom-pipeline
      input:
        url: 'https://app.harness.io/ng/account/Ke-E1FX2SO2ZAL2TXqpLjg/module/idp-admin/orgs/default/projects/airnz/pipelines/New_Service_Onboarding/pipeline-studio?storeType=INLINE'
        inputset:
          owner: ${{ parameters.owner }}
        apikey: ${{ parameters.token }}

  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}

